#!/usr/bin/env python3
"""Inline every CSS file into src/styles.js so content scripts never fetch (strict-CSP sites block fetch). Run after editing CSS."""
import glob, json, os
root = os.path.join(os.path.dirname(__file__), '..')
out = {}
for p in sorted(glob.glob(os.path.join(root, 'src', '**', '*.css'), recursive=True)):
    rel = os.path.relpath(p, root).replace(os.sep, '/')
    out[rel] = open(p, encoding='utf-8').read()
js = '/* GENERATED by scripts/bundle-css.py — do not edit. Edit the .css files and re-run. */\n(function(){const Peel=(window.Peel=window.Peel||{});Peel.css=' + json.dumps(out, ensure_ascii=True) + ';})();\n'
open(os.path.join(root, 'src', 'styles.js'), 'w', encoding='utf-8').write(js)
print('bundled', len(out), 'stylesheets ->', 'src/styles.js')
